dubbo:
    application:
        name: node2
    protocol:
        port: 9012
server:
    port: 9002
spring:
    application:
        name: kvdb-raft-node2
java:
    add-opens:
        java.base/java.lang: ALL-UNNAMED
        java.base/java.math: ALL-UNNAMED
logging:
    # 只有配置了日志文件，才能被监控收集
    file:
        name: logs/${spring.application.name}.log
    #    可单独配置模块日志级别
    #    level:
    #        com.example.kvdbraft: error
cluster:
    my-address: dubbo://localhost:9012
