dubbo:
    application:
        name: node3
    protocol:
        port: 9013
server:
    port: 9003
java:
    add-opens:
        java.base/java.lang: ALL-UNNAMED
        java.base/java.math: ALL-UNNAMED
