dubbo:
    application:
        name: node3
    protocol:
        port: 9013
server:
    port: 9003
spring:
    application:
        name: kvdb-raft-node3
    data:
        redis:
            database: 1
            host: 127.0.0.1
            port: 6373
            password: 123456
java:
    add-opens:
        java.base/java.lang: ALL-UNNAMED
        java.base/java.math: ALL-UNNAMED
node:
    config:
        field:
            shortLeaseTerm: 15
            heartbeatIntervalTime: 10
            electionTimeout: 300
            shardSize: 2
logging:
    # 只有配置了日志文件，才能被监控收集
    file:
        name: logs/${spring.application.name}.log
    #    可单独配置模块日志级别
    #    level:
    #        com.example.kvdbraft: error
cluster:
    my-address: dubbo://localhost:9013
