dubbo:
    protocol:
        name: dubbo
    registry:
        address: zookeeper://${zookeeper.address:127.0.0.1}:2181
    application:
        qos-enable: false
rocksdb:
    dbDir: "./raft/db"
cluster:
    nodes:
        - dubbo://localhost:9011
        - dubbo://localhost:9011
        - dubbo://localhost:9011
