dubbo:
    application:
        name: node1
    protocol:
        port: 9011
server:
    port: 9001
java:
    add-opens:
        java.base/java.lang: ALL-UNNAMED
        java.base/java.math: ALL-UNNAMED
