dubbo:
    protocol:
        name: dubbo
    registry:
        address: zookeeper://${zookeeper.address:127.0.0.1}:2181
    application:
        qos-enable: false
        serialize-check-status: DISABLE

rocksdb:
    dbDir: "./raft/db"
cluster:
    nodes: dubbo://localhost:9011,dubbo://localhost:9012,dubbo://localhost:9013
node:
    config:
        field:
            shortLeaseTerm: 150
            heartbeatIntervalTime: 100
            electionTimeout: 3000
logging:
  # 只有配置了日志文件，才能被监控收集
  file:
    name: logs/kvdb-raft.log
spring:
  main:
    allow-circular-references: true
